import type { Metadata } from "next";
import { Figtree, Roboto, Wix_Madefor_Text } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

// Update the font configuration to ensure it loads correctly
const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-figtree",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-roboto",
});

const wixMadeforText = Wix_Madefor_Text({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-wix-madefor",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${figtree.variable} ${roboto.variable} ${wixMadeforText.variable}`}>
      <body className={`antialiased ${figtree.className}`}>{children}
        <Analytics />
      </body>
    </html>
  );
}
